### ISSUE TITLE
How to run this in local env for development?

### ISSUE THREAD

**Issue by manosamy** [aws-samples/aws-bookstore-demo-app#1]
The react app seems to run locally, but it connects to AWS for Cognito and Lambda functions, how to unit test those services (build, debug, test cycle)?

Where is the code for those lambda functions btw, couldn't find it in this repository?

**Comment by rbboimer** [comment]
During development we’ve been testing directly through the [Lambda console](https://docs.aws.amazon.com/lambda/latest/dg/getting-started-create-function.html) and [API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-test-method.html). 

If you’re interested in testing the Lambda functions locally a common approach would be to use the [AWS SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-reference.html). You will need the functions saved locally to do so. Currently, you can find the functions in the Lambda console by launching the CloudFormation template. We will add them to the repo shortly to make it easier to browse through the code without deploying.

**Comment by rbboimer** [comment]
We've uploaded the Lambda function code, you can now find it under the functions/APIs folder

**Comment by rbboimer** [comment]
Closing this issue. Please reopen if you have any further questions.
