### ISSUE TITLE
Deployment on cloud Formation.

### ISSUE THREAD

**Issue by Bhirpara** [aws-samples/aws-bookstore-demo-app#12]
As i'm trying to follow the steps in getting started. it shows me a rollback error of the lambs functions. is there any other way to run the code.

**Comment by smohiuddin** [comment]
Hi, thanks for your filing an issue. 

What region are you running the template in?

**Comment by Bhirpara** [comment]
> Hi, thanks for your filing an issue.
> 
> What region are you running the template in?
i'm running it in us-east-1

**Comment by smohiuddin** [comment]
Can you share the first error that you see when deploying the CloudFormation template?

A common issue is ensuring you are setting a unique name for AssetsBucketName since S3 buckets are globally unique.

**Comment by Bhirpara** [comment]
> Can you share the first error that you see when deploying the CloudFormation template?
> 
> A common issue is ensuring you are setting a unique name for AssetsBucketName since S3 buckets are globally unique.

![Screen Shot 2019-05-30 at 3 46 23 PM](https://user-images.githubusercontent.com/51133648/58659941-31295680-82f2-11e9-899b-9d48b8d6acaa.png)

**Comment by smohiuddin** [comment]
Please email us at dbaa-github-demos@amazon.com and we would be happy to provide you additional support.

**Comment by beckot** [comment]
@Bhirpara: after deleting my default VPC, I got this to deploy successfully. 

Found the solution through Googling for [this](https://github.com/widdix/aws-cf-templates/issues/37) error.
