### ISSUE TITLE
Running it locally

### ISSUE THREAD

**Issue by Bhirpara** [aws-samples/aws-bookstore-demo-app#13]
while trying to clone and running it locally. i'm facing this error.

fatal: unable to access 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/store-WebAssets/': The requested URL returned error: 403

**Comment by smohiuddin** [comment]
Hi, have you checked our instructions for checking out the repository here: https://github.com/aws-samples/aws-bookstore-demo-app#running-your-web-application-locally

Here's also a getting started guide for using CodeCommit: https://docs.aws.amazon.com/codecommit/latest/userguide/getting-started.html#getting-started-permissions
