### ISSUE TITLE
UpdateSearchCluster lambda: Unable to import module 'index': No module named index

### ISSUE THREAD

**Issue by deki** [aws-samples/aws-bookstore-demo-app#15]
**Describe the bug**
When updating an item DynamoDB Streams should update the search index. However next to the trigger in the table is shown _PROBLEM: Function call failed_ and looking at the CloudWatch logs of UpdateSearchCluster lambda shows _Unable to import module 'index': No module named index_

**To Reproduce**
1. Do a fresh deployment in us-east-1
2. Modify some item
3. Look at the trigger/ cloudwatch logs of UpdateSearchCluster lambda function

**Expected behavior**
No error message.

**Comment by smohiuddin** [comment]
Hi, 

We have resolved the issue and updated the UpdateSearchCluster function.

Thanks for raising the issue.

**Comment by ramuvvy** [comment]
Hello Mohiuddin,

I am trying to setup a lambda function to notify about ssl certificate expiry information well in advance.   I have created function with Python 2.7 runtime and index.lambda_handler.  I have attached code.  When I test it, I am getting below error:

{
  "errorMessage": "Unable to import module 'index'"
}
-----------
START RequestId: b50a27a6-ad29-48a9-8af5-49e77e7b8557 Version: $LATEST
Unable to import module 'index': No module named index


Please check and help me here.  Thanks.
[acm_lambda.txt](https://github.com/aws-samples/aws-bookstore-demo-app/files/4214825/acm_lambda.txt)
