### ISSUE TITLE
Add frontend source code?

### ISSUE THREAD

**Issue by foo123** [aws-samples/aws-bookstore-demo-app#17]
Is it possible to add the frontend source code, plus a couple of guidelines on how to integrate the backend serverless components with the front end?

I am building a project and researching going serverless and it would be really valuable.

Thank you.

**Comment by rbboimer** [comment]
Hello,

You can find the frontend code in the [assets folder](https://github.com/aws-samples/aws-bookstore-demo-app/tree/master/assets). 

In our app we set up the configuration for API Gateway endpoint through the config.ts file, and have [Lambdas](https://github.com/aws-samples/aws-bookstore-demo-app/tree/master/functions/APIs) attached to their respective APIs.

**Comment by foo123** [comment]
Missed that. Great thanks!
