### ISSUE TITLE
Codepipeline build stage failing with "Package 'graphql' support only TS versions that are >=4.1.0"

### ISSUE THREAD

**Issue by rgupta0110** [aws-samples/aws-bookstore-demo-app#28]
Codepipeline build stage is failing with "Package 'graphql' support only TS versions that are >=4.1.0". Here is the complete error. Any quick fixes I can try ?

Creating an optimized production build...
Failed to compile.

/codebuild/output/src957309149/src/node_modules/graphql/NotSupportedTSVersion.d.ts
TypeScript error in /codebuild/output/src957309149/src/node_modules/graphql/NotSupportedTSVersion.d.ts(1,63):
Identifier expected.  TS1003

  > 1 | "Package 'graphql' support only TS versions that are >=4.1.0".
      |                                                               ^

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-bookstore-demo-app@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-bookstore-demo-app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-07T22_47_43_594Z-debug.log

[Container] 2021/11/07 22:47:43 Command did not exit successfully npm run build exit status 1
[Container] 2021/11/07 22:47:43 Phase complete: BUILD State: FAILED

**Comment by MattMcClernon** [comment]
I was able to workaround this issue by making 3 changes...

1) Change the Typescript version to 4.1.0 in assets/package.json
2) Add dependency "@types/history": "^4.1.0" into assets/package.json
3) Added parameter "useUnknownInCatchVariables": false to assets/tsconfig.json

**Comment by Jkudjo** [comment]
@MattMcClernon  This helped thanks

**Comment by Moise1** [comment]
@MattMcClernon or @Jkudjo, do you do the above changes manually? Where is that assets/package.json  file located?

Thanks.
