### ISSUE TITLE
AWS-bookstore-demo-app failing to deploy

### ISSUE THREAD

**Issue by pierrerajha** [aws-samples/aws-bookstore-demo-app#29]
The template would't deploy due to limitted access to sd-aws-wildrydes-us-west-2/aws-serverless-codecommit-seeder.zip.

Cloudformation Error:

CREATE_FAILED | Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for fsd-aws-wildrydes-us-west-2/aws-serverless-codecommit-seeder.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: 807f6f50-152f-49e2-b2e2-8848d6376073, Extended Request ID: null)" (RequestToken: 0b0a339e-fb38-550c-b2ae-2d9d2605a2b9, HandlerErrorCode: AccessDenied)

This is causing SeederFunction to fail to deploy.

To reproduce, simply deploy the the project with cloudformation.
<img width="1471" alt="Screen Shot 2021-12-21 at 4 02 23 PM" src="https://user-images.githubusercontent.com/32343974/147013054-ce9ad34b-4214-4a61-8c55-0648418b12b6.png">

**Comment by jakebracey** [comment]
Also having same issue

**Comment by ja5on6** [comment]
Also having same issue

**Comment by HalinGG** [comment]
I face the same issue.

**Comment by Muksvso** [comment]
I have the same issue, Followed the VPC solution to delete the default VPC in a closed issue here. Worth noting I am new to AWS and using an Always free account. Also I didn't put anything in IAM roles and let it use my identity as an owner and checked the box to confirm that IAM has my permissions to assume my identity/use my access for resource creation. It is the same message but posting to confirm.

Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for fsd-aws-wildrydes-us-west-2/aws-serverless-codecommit-seeder.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: 1457a6c7-9d23-4891-a68c-a9606c7805f5, Extended Request ID: null)" (RequestToken: 75ec818d-94da-fb62-7ac6-ccc1968680e2, HandlerErrorCode: AccessDenied)

**Comment by expresslaw** [comment]
Same issure here..... Apparantly whoever owns the buckets for this code (fsd-aws-wildrydes-<region>/) has disabled GetObject for either public read or even authenticated users. This is very disappointing as it looks to be a great demo and I'd really like to run it.

**Comment by sebastienpiette** [comment]
Same issue here. No Update yet as of 28 March 2022 ? Whoever knows the owner of the failing bucket...please help :))) 
fsd-aws-wildrydes-eu-central-1/aws-serverless-codecommit-seeder.zip

**Comment by triggan** [comment]
Hi all,

I've fixed a number of issues with the stack and updated the primary template.  This should now deploy successfully.  Apologies for the lack of response.  We're in the process of reviving this stack for some upcoming workshops.

Please feel free to open any new issues that you might encounter.

**Comment by waelsv** [comment]
@triggan I'm not sure this was fixed as I'm facing the same issue with this template:
