### ISSUE TITLE
Add mappings to other regions or static reference to S3Bucket w/o AWS::region as it only exist in us-east-1..

### ISSUE THREAD

**Issue by deejvince** [aws-samples/aws-bookstore-demo-app#3]
Hello,

When trying to deploy to different regions, there's an error returned.
After digging into the CFN template, it seems that there's only a bucket for the assets in us-east-1, but in references to the S3Bucket mapping, the template maps AWS::Region, like so:
S3Bucket: !FindInMap 
          - S3Buckets
          - !Ref 'AWS::Region'
          - Bucket

Suggest to keep the region static or deploy the code in buckets on other regions.

**Comment by smohiuddin** [comment]
Hi, 

Thank you for your feedback!

We have added support for:

- US West (Oregon) us-west-2 
- EU (Frankfurt) eu-central-1
- EU (Ireland) eu-west-1
