### ISSUE TITLE
Template linked in advanced section does not match the one in the git repo

### ISSUE THREAD

**Issue by deejvince** [aws-samples/aws-bookstore-demo-app#4]
In this section in readme.md its mentioned:

> Advanced: The source CloudFormation template is available here. and links to: 

`https://s3.amazonaws.com/aws-bookstore-demo/master-fullstack.template`

but the template there is not the same as the one on this repo (for example the constants section is shorter)..

**Comment by smohiuddin** [comment]
Thank you for filing this issue and sorry for the delay!
We have updated the template on our S3 bucket to be consistent with the GitHub repo.
