### ISSUE TITLE
Search not displaying results

### ISSUE THREAD

**Issue by audioe** [aws-samples/aws-bookstore-demo-app#41]
**Describe the bug**
Search not displaying results in webpage, but can see results are being returned by lambda function when testing through Search API or viewing cloudwatch logs for Lambda Function.

**To Reproduce**
1. Search for any known book in database
2. Click enter or hit Search

**Expected behavior**
Search results should be displayed on webspage

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by triggan** [comment]
This should be fixed via the reason mentioned in Issue #40 .  If this is still an issue, please re-open and provide more detail of what is being seen by the browser via the browser's Developer Tools.
