### ISSUE TITLE
Images in the store are very big (on s3)

### ISSUE THREAD

**Issue by deejvince** [aws-samples/aws-bookstore-demo-app#6]
**Describe the bug**
The item images are very big (1-2mb each),
as a result, it takes time to render the page and the result seems sluggish.
The purpose of this demo is to give a "Right database tool for the job" demo, but when showing the demo, it gives the impression of a slow sluggish app - hench it's not a good show.. :)

Also, you're using Cloudfront to serve the app, why not add another behaviour to cache objects from S3 rather then directly linking to an S3 bucket? this should also speed things up.

**To Reproduce**
Just move and load diffrent categories of items in the app,
Each image takes long time to load.

**Expected behavior**
faster page load times.

Thank you

**Comment by smohiuddin** [comment]
Hi, thanks for the feedback. 

We've reduced the image sizes significantly and moved to serving via CloudFront.
